spring.application.name=login-registration

spring.datasource.url=jdbc:postgresql://dpg-d8ttgrnavr4c73a22jsg-a.oregon-postgres.render.com:5432/printer_db_60ga
spring.datasource.username=printer_db_60ga_user
spring.datasource.password=TiKy13IFab7aXV3nvlhKkqImMROtDvbl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false




razorpay.key.id=rzp_live_T87am8Vgt9W2O9
razorpay.key.secret=tAOXxWJ2ou8xS0nrD3WOWSxZ
 



server.port=${PORT:8080}

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false

print.agent.enabled=true
print.cancel-window-seconds=30

# Remove PDF blob 30 minutes after order is completed
print.pdf.retention-minutes=5

# Also wipe finished-order PDF data every day at 2:00 AM
print.pdf.daily-cleanup-enabled=true
print.pdf.daily-cleanup-cron=0 0 2 * * *

# Auto-cancel and wallet refund if print not completed within 5 minutes
print.fulfillment-timeout-minutes=5

# SMTP Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:saipraveendasari1@gmail.com}
spring.mail.password=${MAIL_PASSWORD:xlcsaxdlefpogkxl}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Spring Security OAuth2 Kiosk Credentials Configuration
# Fill in these credentials from your Google and Microsoft Developer portals to enable social login:
spring.security.oauth2.client.registration.google.client-id=376509456659-c49lc954jdp6a2lmautbdo2umbo3t1mn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=****0zod
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.azure.client-id=your-azure-client-id
spring.security.oauth2.client.registration.azure.client-secret=your-azure-client-secret
spring.security.oauth2.client.registration.azure.scope=openid,profile,email,User.Read
spring.security.oauth2.client.registration.azure.client-name=Microsoft
spring.security.oauth2.client.provider.azure.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.azure.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.azure.jwk-set-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys
spring.security.oauth2.client.provider.azure.user-info-uri=https://graph.microsoft.com/v1.0/me
spring.security.oauth2.client.provider.azure.user-name-attribute=displayName

# Frontend Application Redirection URL for Production deployment
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}


